from typing import Protocol, List, Dict, Any

class ITool(Protocol):
    def execute(self, **kwargs) -> Any:
        ...
    def get_capabilities(self) -> Dict[str, Any]:
        ...

class IPlanner(Protocol):
    def generate_plan(self, intent: str, context: Dict[str, Any]) -> List[str]:
        ...

class IExecutor(Protocol):
    def run(self, plan: List[str]) -> Dict[str, Any]:
        ...

class IAgent(Protocol):
    def initialize(self) -> None:
        ...
    def execute(self, task: str) -> str:
        ...
    def pause(self) -> None:
        ...
    def resume(self) -> None:
        ...
