import { motion, AnimatePresence } from 'framer-motion';
import { X, BrainCircuit, ShieldCheck, CheckCircle2, AlertCircle } from 'lucide-react';
import type { ContextExplanation } from '../../../core/models';

interface AIExplanationPanelProps {
  isOpen: boolean;
  onClose: () => void;
  explanation: ContextExplanation;
  title: string;
}

export function AIExplanationPanel({ isOpen, onClose, explanation, title }: AIExplanationPanelProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm"
          onClick={onClose}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-lg bg-card border border-border shadow-2xl rounded-2xl overflow-hidden flex flex-col"
          >
            <div className="flex items-center justify-between p-4 border-b border-border bg-secondary/30">
              <div className="flex items-center gap-2">
                <BrainCircuit className="w-5 h-5 text-purple-500" />
                <h2 className="font-semibold text-sm">AI Explanation</h2>
              </div>
              <button 
                onClick={onClose}
                className="p-1.5 text-muted-foreground hover:bg-secondary rounded-md transition-colors"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-6 overflow-y-auto max-h-[70vh]">
              <div>
                <h3 className="text-xl font-bold mb-1">{title}</h3>
                <div className="flex items-center gap-3 mt-2">
                  <div className="flex items-center gap-1.5 text-sm font-medium text-emerald-500 bg-emerald-500/10 px-2 py-1 rounded-full border border-emerald-500/20">
                    <ShieldCheck className="w-4 h-4" />
                    {explanation.confidence_score}% Confidence
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <div className="bg-secondary/30 p-4 rounded-xl border border-border">
                  <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2 flex items-center gap-2">
                    <AlertCircle className="w-4 h-4" /> Why this appears
                  </h4>
                  <p className="text-sm">{explanation.reason}</p>
                </div>

                <div className="bg-blue-500/5 p-4 rounded-xl border border-blue-500/20">
                  <h4 className="text-xs font-semibold uppercase tracking-wider text-blue-500 mb-2 flex items-center gap-2">
                    <TrendingUpIcon className="w-4 h-4" /> Expected Impact
                  </h4>
                  <p className="text-sm text-foreground">{explanation.expected_impact}</p>
                </div>

                <div className="bg-emerald-500/5 p-4 rounded-xl border border-emerald-500/20">
                  <h4 className="text-xs font-semibold uppercase tracking-wider text-emerald-500 mb-2 flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4" /> Recommended Action
                  </h4>
                  <p className="text-sm text-foreground">{explanation.recommended_action}</p>
                </div>

                {explanation.supporting_evidence && explanation.supporting_evidence.length > 0 && (
                  <div>
                    <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">Supporting Evidence</h4>
                    <ul className="space-y-2">
                      {explanation.supporting_evidence.map((evidence: string, i: number) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                          <span className="w-1.5 h-1.5 rounded-full bg-border mt-1.5 shrink-0" />
                          <span>{evidence}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </div>
            
            <div className="p-4 border-t border-border bg-secondary/30 text-xs text-muted-foreground text-center flex items-center justify-center gap-2">
               <ShieldCheck className="w-4 h-4" />
               Generated by PFOS Decision Intelligence Platform
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

function TrendingUpIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>
  );
}
